version: '3.8'

services:
  web:
    image: ddeityy/g_4_10:djangunicorn
    command: gunicorn djangodocker.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    image: ddeityy/g_4_10:nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
